[package]
name = "auth-service"
version = "0.1.0"
authors = ["Quentin Gliech <quentingliech@gmail.com>"]

[dependencies]
clap = "~2.20.0"
iron = "0.4.*"
serde = "0.8"
serde_json = "0.8"
serde_derive = "0.8"

[dependencies.toml]
version = "0.2"
default-features = false
features = ["serde"]
